services:
  frontend:
    image: frontend
    build: ./frontend
    command: npm start
    environment:
      REACT_APP_API_URL: http://127.0.0.1:8080
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 3000:3000
    depends_on:
      - backend

  frontend-css:
    image: frontend-css
    build: ./frontend
    command: npm run build-css
    tty: true
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - frontend

  backend:
    image: backend
    build: ./backend
    volumes:
      - ./backend/src:/backend/src
      - ./backend/public:/backend/public
    environment:
      PORT: 8080
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_URI: ${MONGO_URI}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_APPNAME: ${MONGO_APPNAME}

    ports:
      - 8080:8080
    env_file: .env
